//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlatFile()
        {
            this.PolicyD = new HashSet<PolicyD>();
        }
    
        public int FlatFileId { get; set; }
        public string Policy_No { get; set; }
        public string Serial_No { get; set; }
        public string Contract_No { get; set; }
        public Nullable<System.DateTime> Contract_eff_date { get; set; }
        public Nullable<System.DateTime> Contract_exp_date { get; set; }
        public Nullable<System.DateTime> Contract_canel_dt { get; set; }
        public string Model_nm { get; set; }
        public Nullable<decimal> Gr_Prem_amt { get; set; }
        public Nullable<decimal> Handling_fee { get; set; }
        public Nullable<int> FlatFileStatus { get; set; }
        public Nullable<bool> FlatFileIsDeleted { get; set; }
        public Nullable<int> FlatFileCreatedId { get; set; }
        public Nullable<System.DateTime> FlatFileCreatedDate { get; set; }
        public Nullable<int> FlatFileEditedId { get; set; }
        public Nullable<System.DateTime> FlatFileEditedDate { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyD> PolicyD { get; set; }
    }
}
