//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatFileTemp
    {
        public string AppleCareContractNumber { get; set; }
        public string SerialNumber { get; set; }
        public string AIGContractNumber { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<decimal> Gr_Prem_amt { get; set; }
        public Nullable<decimal> Handling_fee { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Status { get; set; }
        public int FlatFileTempId { get; set; }
    }
}
