//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyAc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyAc()
        {
            this.PolicyD = new HashSet<PolicyD>();
        }
    
        public string PolicyAcYear { get; set; }
        public int PolicyAcNo { get; set; }
        public Nullable<System.DateTime> PolicyAc_pol_eff_date { get; set; }
        public Nullable<System.DateTime> PolicyAc_pol_exp_date { get; set; }
        public string PolicyAc_client_nm { get; set; }
        public string PolicyAc_id_no { get; set; }
        public string PolicyAc_line_1_addr { get; set; }
        public Nullable<System.DateTime> PolicyAc_timestamp { get; set; }
        public string PolicyAc_QR_Code { get; set; }
        public Nullable<decimal> PolicyAc_premuim_all { get; set; }
        public Nullable<int> PolicyAcStatus { get; set; }
        public Nullable<System.DateTime> PolicyAcCreatedDate { get; set; }
        public Nullable<int> PolicyAcEditedId { get; set; }
        public Nullable<System.DateTime> PolicyAcEditedDate { get; set; }
        public Nullable<bool> PolicyAcIsDeleted { get; set; }
        public string PolicyAc_NuclearPDF { get; set; }
        public string PolicyAc_tran_id { get; set; }
        public int PolicyAcId { get; set; }
        public int PolicyAc_receiptNO { get; set; }
        public Nullable<System.DateTime> PolicyAcBillingDate { get; set; }
        public string PolicyAcXmlURL { get; set; }
        public Nullable<int> PolicyAcBatchFileStatus { get; set; }
        public Nullable<int> PolicyAcAmlStatus { get; set; }
        public Nullable<int> PolicyAc_endorsement_no { get; set; }
        public string PolicyAc_line_2_addr { get; set; }
        public string PolicyAc_receiptNO_All { get; set; }
        public string PolicyAc_PolicyNO_All { get; set; }
        public string PolicyAc_store_id { get; set; }
        public Nullable<bool> PolicyAcIsLogout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyD> PolicyD { get; set; }
    }
}
