//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyAc_Eds
    {
        public int PolicyAc_Eds_id { get; set; }
        public Nullable<int> PolicyAc_Eds_status { get; set; }
        public string PolicyAc_Eds_PolicyNO_All { get; set; }
        public string PolicyAc_Eds_endorse_no_All { get; set; }
        public string PolicyAc_Eds_tran_id { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_pol_eff_date { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_pol_exp_date { get; set; }
        public string PolicyAc_Eds_id_no { get; set; }
        public string PolicyAc_Eds_client_nm { get; set; }
        public string PolicyAc_Eds_line_1_addr { get; set; }
        public string PolicyAc_Eds_line_2_addr { get; set; }
        public string PolicyAc_Eds_mobile_no { get; set; }
        public string PolicyAc_Eds_email_addr { get; set; }
        public string PolicyAc_Eds_nationality { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_dob { get; set; }
        public string PolicyAc_Eds_legal_person { get; set; }
        public string PolicyAc_Eds_phone_no { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_endor_eff_date { get; set; }
        public string PolicyAc_Eds_tran_type { get; set; }
        public string PolicyAc_Eds_ins_mobile_serial_no { get; set; }
        public Nullable<decimal> PolicyAc_Eds_refund_amt { get; set; }
        public Nullable<System.DateTime> PolicyAc_EdsCreatedDate { get; set; }
        public Nullable<int> PolicyAc_EdsEditedId { get; set; }
        public Nullable<System.DateTime> PolicyAc_EdsEditedDate { get; set; }
        public Nullable<bool> PolicyAc_EdsIsDeleted { get; set; }
        public string PolicyAc_Eds_XmlURL { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_BillingDate { get; set; }
        public Nullable<int> PolicyAc_Eds_FlatFileId { get; set; }
        public Nullable<int> PolicyAc_Eds_endorsement_no { get; set; }
        public Nullable<int> PolicyAc_Eds_seq_no { get; set; }
        public Nullable<System.DateTime> PolicyAc_Eds_EventDate { get; set; }
    }
}
