//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SidebarMain
    {
        public int SidebarMainId { get; set; }
        public string SidebarMainName { get; set; }
        public Nullable<int> SidebarMainCode { get; set; }
        public string SidebarMainIcon { get; set; }
        public Nullable<int> SidebarMainSort { get; set; }
        public string SidebarMainLink { get; set; }
        public Nullable<bool> SidebarMainStatus { get; set; }
        public Nullable<bool> SidebarMainIsDeleted { get; set; }
        public Nullable<int> SidebarMainCreatedId { get; set; }
        public Nullable<System.DateTime> SidebarMainCreatedDate { get; set; }
        public Nullable<int> SidebarMainEditedId { get; set; }
        public Nullable<System.DateTime> SidebarMainEditedDate { get; set; }
        public Nullable<int> SidebarMainWebsiteId { get; set; }
        public Nullable<bool> SidebarMainOpenAnother { get; set; }
    }
}
