//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AML_PLCY_wk
    {
        public string Insu_type { get; set; }
        public string AML_POLICY { get; set; }
        public string RENL_CERT_NO { get; set; }
        public string AML_Trans_DT { get; set; }
        public string AML_ID { get; set; }
        public string AML_INSURED_NAME { get; set; }
        public Nullable<int> premium_amt { get; set; }
        public string MAJOR_LINE_CD { get; set; }
        public string MINOR_LINE_CD { get; set; }
        public string LOCAL_LOB_CODE { get; set; }
        public string remark { get; set; }
        public string input_id { get; set; }
        public string input_dt { get; set; }
        public string AML_Pol_Incept_DT { get; set; }
        public string BOOKING_No { get; set; }
    }
}
