//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackLog
    {
        public int TrackLogId { get; set; }
        public Nullable<int> TrackLogCode { get; set; }
        public Nullable<int> TrackLogStatus { get; set; }
        public Nullable<int> TrackLogChangeId { get; set; }
        public string TrackLogBefore { get; set; }
        public string TrackLogAfter { get; set; }
        public Nullable<System.DateTime> TrackLogCreatedDate { get; set; }
        public Nullable<bool> TrackLogIsDeleted { get; set; }
        public int TrackLogCreatedId { get; set; }
        public string TrackLogCreatedIP { get; set; }
    }
}
