//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTW_APPLEAPPFORM_DEVICE_PREM_INFO
    {
        public long mobile_id { get; set; }
        public string mobile_type { get; set; }
        public string mobile_model { get; set; }
        public Nullable<decimal> mobile_premium { get; set; }
        public Nullable<long> policy_period { get; set; }
        public Nullable<decimal> mobile_device_price { get; set; }
        public Nullable<decimal> screen_ee_deduct { get; set; }
        public Nullable<decimal> other_deduct { get; set; }
        public Nullable<long> max_claim_count { get; set; }
        public Nullable<System.DateTime> prod_eff_date { get; set; }
        public Nullable<System.DateTime> prod_exp_date { get; set; }
    }
}
