//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserLoginLog = new HashSet<UserLoginLog>();
        }
    
        public int UserId { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string UserPasswordTemp { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserAuthorityId { get; set; }
        public Nullable<int> UserError { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<System.DateTime> UserCreatedDate { get; set; }
        public Nullable<int> UserCreatedId { get; set; }
        public Nullable<int> UserEditedId { get; set; }
        public Nullable<System.DateTime> UserEditedDate { get; set; }
        public Nullable<bool> UserIsDeleted { get; set; }
        public string UserName { get; set; }
        public string UserPasswordAgain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginLog> UserLoginLog { get; set; }
    }
}
