//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginLog
    {
        public int UserLoginLogId { get; set; }
        public string UserLoginLogName { get; set; }
        public Nullable<System.DateTime> UserLoginLogTime { get; set; }
        public string UserLoginLogIP { get; set; }
        public Nullable<int> UserLoginLogStatus { get; set; }
        public string UserLoginLogAccount { get; set; }
        public Nullable<bool> UserLoginLogIsDeleted { get; set; }
        public Nullable<int> UserLoginLogError { get; set; }
        public string UserLoginLogReason { get; set; }
        public Nullable<int> UserLoginLogUserId { get; set; }
        public Nullable<int> UserLoginLogDeLockUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
